module.exports.AREA_SERVICIO = [
    'Affordable and clean energy',
    'Clear water and sanitation',
    'Climate action',
    'Cultural',
    'Cultural Diversity',
    'Decent work and economic growth',
    'Diversity',
    'Gender equality',
    'Good health and well-being',
    'Historic/Cultural preservation',
    'Industry',
    'Industry, innovation and infraestructure',
    'Innovation and infraestructure',
    'Justice and strong institutions',
    'Life below water',
    'Life on land',
    'No poverty',
    'Not Apply',
    'Partnership for the goals',
    'Peace',
    'Peace, justice and strong institutions',
    'Quality education',
    'Reducing inequalities',
    'Responsible consumption and production',
    'Social justice',
    'Sustainable cities and communities',
    'Zero hunger'
];