module.exports.NECESIDAD_SOCIAL = [
    'Actor-Network Theory',
    'Administrative Sciences',
    'Agogic Sciences',
    'Anthropology',
    'Archaelogy',
    'Art for Biodiversity',
    'Arts',
    'Audiovisual Communication',
    'Audiovisual Context',
    'Autism Spectrum',
    'Bilingual literacy',
    'Biology',
    'Business',
    'Business Administration',
    'Business Comunication',
    'Chemistry',
    'Clinical',
    'Communication',
    'Communication Sciences Marketing and Digital Media',
    'Computer Science',
    'Cultural Historical Psychology',
    'Cultural Intelligence',
    'Cultural Studies',
    'Democratic Culture',
    'Dentistry',
    'Development',
    'Didactical',
    'Didactics',
    'Digital Tech',
    'Digital Technologies Education',
    'Earth Sciences',
    'Economics',
    'Education',
    'Education Policies. Education. Service-learning',
    'Education. Service-learning',
    'Education. Service-learning. Research',
    'Educational Policies',
    'Engage learning',
    'Engineering and technology',
    'Evaluation',
    'Foreign Language',
    'Fundamentals of social and legal protection',
    'General',
    'Geography',
    'Geoscience',
    'Gerontology',
    'History',
    'Human Geography',
    'ICT',
    'Information and Communication Sciences',
    'Information Sciences. Education',
    'Innovation',
    'Language Policy',
    'Languages and Literature',
    'Law',
    'Management',
    'Marketing and Advertising',
    'Mathematical',
    'Mathematics',
    'Medicine',
    'Medicine and Health',
    'Methodology',
    'Microbiology',
    'Migration Studies',
    'Nursing',
    'Open to different disciplines',
    'Other',
    'Pedagogy',
    'Pedagogy and Economics',
    'Pedagogy in Sociology',
    'Pedogagy',
    'Performing Arts',
    'Philosophy',
    'Physical Education',
    'Physical Education and Sport',
    'Physics',
    'Physioterapy',
    'Plastics',
    'Political Science',
    'Primary Education Teaching',
    'Physochology',
    'Public Health',
    'Public Management',
    'Quality Assessment',
    'Research Users',
    'Rural Development',
    'Social Economy',
    'Social Education',
    'Social Justice',
    'Social Science',
    'Social Work',
    'Sociology',
    'Space Science',
    'Statistics',
    'Theology',
    'Third Sector',
    'Transcersal Competences',
    'Virtual Mobility',
    'Youth Policy'

];