import { AceptacionAceptada } from './services/types/AceptacionAceptada';
import { AceptacionRechazada } from './services/types/AceptacionRechazada';
import { Admin } from './services/types/Admin';
import { AnuncioServicio } from './services/types/AnuncioServicio';
import { AreaConocimiento } from './services/types/AreaConocimiento';
import { AreaConocimiento_Profesor } from './services/types/AreaConocimiento_Profesor';
import { AreaServicio } from './services/types/AreaServicio';
import { AreaServicio_AnuncioServicio } from './services/types/AreaServicio_AnuncioServicio';
import { AreaServicio_Iniciativa } from './services/types/AreaServicio_Iniciativa';
import { Asignatura } from './services/types/Asignatura';
import { Colaboracion } from './services/types/Colaboracion';
import { Colaborador } from './services/types/Colaborador';
import { DatosPersonalesExterno } from './services/types/DatosPersonalesExterno';
import { DatosPersonalesInterno } from './services/types/DatosPersonalesInterno';
import { DemandaRespalda } from './services/types/DemandaRespalda';
import { DemandaServicio } from './services/types/DemandaServicio';
import { Estudiante } from './services/types/Estudiante';
import { EstudianteExterno } from './services/types/EstudianteExterno';
import { EstudianteInterno } from './services/types/EstudianteInterno';
import { EstudianteProyecto } from './services/types/EstudianteProyecto';
import { Iniciativa } from './services/types/Iniciativa';
import { Mail } from './services/types/Mail';
import { Matching } from './services/types/Matching';
import { MatchingArea } from './services/types/MatchingArea';
import { MatchingAreaServicioTitulacion } from './services/types/MatchingAreaServicioTitulacion';
import { Mensaje } from './services/types/Mensaje';
import { MensajeAnuncioServicio } from './services/types/MensajeAnuncioServicio';
import { MensajeColaboracion } from './services/types/MensajeColaboracion';
import { NecesidadSocial } from './services/types/NecesidadSocial';
import { Newsletter } from './services/types/Newsletter';
import { Nota } from './services/types/Nota';
import { Notificacion } from './services/types/Notificacion';
import { NotificacionMatching } from './services/types/NotificacionMatching';
import { OfertaAceptada } from './services/types/OfertaAceptada';
import { OfertaDemanda_Tags } from './services/types/OfertaDemanda_Tags';
import { OfertaServicio } from './services/types/OfertaServicio';
import { OficinaAps } from './services/types/OficinaAps';
import { Partenariado } from './services/types/Partenariado';
import { PartenariadoRellenado } from './services/types/PartenariadoRellenado';
import { PrevioPartenariado } from './services/types/PrevioPartenariado';
import { Profesor } from './services/types/Profesor';
import { ProfesorExterno } from './services/types/ProfesorExterno';
import { ProfesorInterno } from './services/types/ProfesorInterno';
import { ProfesorInterno_Oferta } from './services/types/ProfesorInterno_Oferta';
import { Profesor_Colaboracion } from './services/types/Profesor_Colaboracion';
import { Proyecto } from './services/types/Proyecto';
import { SocioComunitario } from './services/types/SocioComunitario';
import { Tag } from './services/types/Tag';
import { TitulacionLocal } from './services/types/TitulacionLocal';
import { TitulacionLocal_Demanda } from './services/types/TitulacionLocal_Demanda';
import { TitulacionLocal_Profesor } from './services/types/TitulacionLocal_Profesor';
import { TutorCA } from './services/types/TutorCA';
import { Universidad } from './services/types/Universidad';
import { Upload } from './services/types/Upload';
import { Upload_AnuncioServicio } from './services/types/Upload_AnuncioServicio';
import { Upload_Colaboracion } from './services/types/Upload_Colaboracion';
import { Usuario } from './services/types/Usuario';
import { ViewNotification } from './services/types/views/Notification';
import { ViewNotificationBackedDemand } from './services/types/views/NotificationBackedDemand';
import { ViewNotificationConfirmationAccepted } from './services/types/views/NotificationConfirmationAccepted';
import { ViewNotificationConfirmationRejected } from './services/types/views/NotificationConfirmationRejected';
import { ViewNotificationMatchingNotification } from './services/types/views/NotificationMatchingNotification';
import { ViewNotificationOfferAccepted } from './services/types/views/NotificationOfferAccepted';
import { ViewNotificationPartnershipFilled } from './services/types/views/NotificationPartnershipFilled';
import { ViewPartnership } from './services/types/views/Partnership';
import { ViewServiceOffer } from './services/types/views/ServiceOffer';
import { ViewUser } from './services/types/views/User';
import { ViewUserAdmin } from './services/types/views/UserAdmin';
import { ViewUserApSOffice } from './services/types/views/UserApSOffice';
import { ViewUserCommunityPartner } from './services/types/views/UserCommunityPartner';
import { ViewUserExternalProfessor } from './services/types/views/UserExternalProfessor';
import { ViewUserExternalStudent } from './services/types/views/UserExternalStudent';
import { ViewUserInternalProfessor } from './services/types/views/UserInternalProfessor';
import { ViewUserInternalStudent } from './services/types/views/UserInternalStudent';
import { ViewUserPrivileged } from './services/types/views/UserPrivileged';

declare module 'knex/types/tables' {
	interface Tables {
		// Views
		[ViewUser.Name]: ViewUser.RawValue;
		[ViewUserAdmin.Name]: ViewUserAdmin.Value;
		[ViewUserExternalStudent.Name]: ViewUserExternalStudent.Value;
		[ViewUserExternalProfessor.Name]: ViewUserExternalProfessor.RawValue;
		[ViewUserInternalStudent.Name]: ViewUserInternalStudent.Value;
		[ViewUserInternalProfessor.Name]: ViewUserInternalProfessor.Value;
		[ViewUserApSOffice.Name]: ViewUserApSOffice.Value;
		[ViewUserCommunityPartner.Name]: ViewUserCommunityPartner.Value;
		[ViewUserPrivileged.Name]: ViewUserPrivileged.Value;
		[ViewPartnership.Name]: ViewPartnership.Value;
		[ViewServiceOffer.Name]: ViewServiceOffer.RawValue;
		[ViewNotification.Name]: ViewNotification.Value;
		[ViewNotificationConfirmationAccepted.Name]: ViewNotificationConfirmationAccepted.Value;
		[ViewNotificationConfirmationRejected.Name]: ViewNotificationConfirmationRejected.Value;
		[ViewNotificationBackedDemand.Name]: ViewNotificationBackedDemand.Value;
		[ViewNotificationMatchingNotification.Name]: ViewNotificationMatchingNotification.Value;
		[ViewNotificationOfferAccepted.Name]: ViewNotificationOfferAccepted.Value;
		[ViewNotificationPartnershipFilled.Name]: ViewNotificationPartnershipFilled.Value;

		// Tables
		[AceptacionAceptada.Name]: AceptacionAceptada.Value;
		[AceptacionRechazada.Name]: AceptacionRechazada.Value;
		[Admin.Name]: Admin.Value;
		[AnuncioServicio.Name]: AnuncioServicio.Value;
		[AreaConocimiento_Profesor.Name]: AreaConocimiento_Profesor.Value;
		[AreaConocimiento.Name]: AreaConocimiento.Value;
		[AreaServicio_AnuncioServicio.Name]: AreaServicio_AnuncioServicio.Value;
		[AreaServicio_Iniciativa.Name]: AreaServicio_Iniciativa.Value;
		[AreaServicio.Name]: AreaServicio.Value;
		[Asignatura.Name]: Asignatura.Value;
		[Colaboracion.Name]: Colaboracion.Value;
		[DatosPersonalesExterno.Name]: DatosPersonalesExterno.Value;
		[DatosPersonalesInterno.Name]: DatosPersonalesInterno.Value;
		[DemandaRespalda.Name]: DemandaRespalda.Value;
		[DemandaServicio.Name]: DemandaServicio.Value;
		[Estudiante.Name]: Estudiante.Value;
		[EstudianteExterno.Name]: EstudianteExterno.Value;
		[EstudianteInterno.Name]: EstudianteInterno.Value;
		[EstudianteProyecto.Name]: EstudianteProyecto.Value;
		[Iniciativa.Name]: Iniciativa.Value;
		[Mail.Name]: Mail.Value;
		[Matching.Name]: Matching.Value;
		[MatchingArea.Name]: MatchingArea.Value;
		[MatchingAreaServicioTitulacion.Name]: MatchingAreaServicioTitulacion.Value;
		[Mensaje.Name]: Mensaje.Value;
		[MensajeAnuncioServicio.Name]: MensajeAnuncioServicio.Value;
		[MensajeColaboracion.Name]: MensajeColaboracion.Value;
		[NecesidadSocial.Name]: NecesidadSocial.Value;
		[Newsletter.Name]: Newsletter.Value;
		[Nota.Name]: Nota.Value;
		[Notificacion.Name]: Notificacion.Value;
		[NotificacionMatching.Name]: NotificacionMatching.Value;
		[OfertaAceptada.Name]: OfertaAceptada.Value;
		[OfertaDemanda_Tags.Name]: OfertaDemanda_Tags.Value;
		[OfertaServicio.Name]: OfertaServicio.Value;
		[OficinaAps.Name]: OficinaAps.Value;
		[Partenariado.Name]: Partenariado.Value;
		[PartenariadoRellenado.Name]: PartenariadoRellenado.Value;
		[PrevioPartenariado.Name]: PrevioPartenariado.Value;
		[Profesor_Colaboracion.Name]: Profesor_Colaboracion.Value;
		[Profesor.Name]: Profesor.Value;
		[ProfesorExterno.Name]: ProfesorExterno.Value;
		[ProfesorInterno_Oferta.Name]: ProfesorInterno_Oferta.Value;
		[ProfesorInterno.Name]: ProfesorInterno.Value;
		[Proyecto.Name]: Proyecto.Value;
		[SocioComunitario.Name]: SocioComunitario.Value;
		[Tag.Name]: Tag.Value;
		[TitulacionLocal_Demanda.Name]: TitulacionLocal_Demanda.Value;
		[TitulacionLocal_Profesor.Name]: TitulacionLocal_Profesor.Value;
		[TitulacionLocal.Name]: TitulacionLocal.Value;
		[Universidad.Name]: Universidad.Value;
		[Upload_AnuncioServicio.Name]: Upload_AnuncioServicio.Value;
		[Upload_Colaboracion.Name]: Upload_Colaboracion.Value;
		[Upload.Name]: Upload.Value;
		[Usuario.Name]: Usuario.Value;
		[TutorCA.Name]: TutorCA.Value;
		[Colaborador.Name]: Colaborador.Value;
	}
}
