module.exports.ROL_ESTUDIANTE = 'ROL_ESTUDIANTE';
module.exports.ROL_PROFESOR = 'ROL_PROFESOR';
module.exports.ROL_SOCIO_COMUNITARIO = 'ROL_SOCIO_COMUNITARIO';
module.exports.ROL_GESTOR = 'ROL_GESTOR';

module.exports.ROLES = [
    'ROL_ESTUDIANTE',
    'ROL_PROFESOR',
    'ROL_SOCIO_COMUNITARIO',
    'ROL_GESTOR',
];